// src/contexts/TextContext.jsx
import { createContext, useContext, useState } from 'react';

const TextContext = createContext();

export const useText = () => useContext(TextContext);

const translations = {
    en: {
        previous: "Previous",
        next: "Next",
        hideanswer: "Hide Answer",
        showanswer: "Show Answer",
        youranswer: "Your Answer",
        translation: "Translation",
        correctanswer: "Correct Answer", 
        prompt: "Prompt",
        title_1: "Latin Phrase Memorization",
        prompt_1: "In the name of the Father, and of the Son, and of the Holy Spirit. Amen. I will go to the altar of God.",
        prompt_2: "Judge me, O God, and distinguish my cause from the nation that is not holy: deliver me from the unjust and deceitful man.",
        prompt_3: "Send forth thy light and thy truth: they have led me and brought me unto thy holy hill, and into thy tabernacles.",
        prompt_4: "I will praise thee upon the harp, O God, my God: why art thou sad, O my soul, and why dost thou disquiet me?",
        prompt_5: "Glory be to the Father, and to the Son, and to the Holy Spirit.",
        prompt_6: "I will go to the altar of God.",
        prompt_7: "Our help is in the name of the Lord",
        prompt_8: "I confess to almighty God, to blessed Mary ever Virgin, to blessed Michael the Archangel, to blessed John the Baptist, to the holy Apostles Peter and Paul, to all the Saints, and to you, brethren, that I have sinned exceedingly in thought, word, and deed: through my fault, through my fault, through my most grievous fault. Therefore I beseech blessed Mary ever Virgin, blessed Michael the Archangel, blessed John the Baptist, the holy Apostles Peter and Paul, all the Saints, and you, brethren, to pray for me to the Lord our God.",
        prompt_9: "Amen",
        prompt_10: "May almighty God have mercy on you, and having forgiven your sins, bring you to life everlasting.",
        prompt_11: "May the almighty and merciful Lord grant us pardon, absolution, and remission of our sins.",
        prompt_12: "Thou wilt turn, O God, and bring us to life.",
        prompt_13: "Show us, O Lord, thy mercy.",
        prompt_14: "O Lord, hear my prayer.",
        prompt_15: "The Lord be with you.",
        ans_1: "To God who gives joy to my youth",
        ans_2: "Because you, O God, are my strength: Why have you rejected me? And why do I go sorrowful while the enemy afflicts me?",
        ans_3: "And I will go unto the altar of God: to God who gives joy to my youth.",
        ans_4: "Hope in God, for I will still praise Him: the salvation of my countenance, and my God.",
        ans_5: "As it was in the beginning, is now, and ever shall be: world without end. Amen.",
        ans_6: "To God, who gives joy to my youth.",
        ans_7: "Who made heaven and earth.",
        ans_8: "May almighty God have mercy on you, and having forgiven your sins, bring you to life everlasting.",
        ans_9: "I confess to almighty God, to blessed Mary ever Virgin, to blessed Michael the Archangel, to blessed John the Baptist, to the holy Apostles Peter and Paul, to all the Saints, and to you, father, that I have sinned exceedingly in thought, word, and deed: through my fault, through my fault, through my most grievous fault. Therefore I beseech blessed Mary ever Virgin, blessed Michael the Archangel, blessed John the Baptist, the holy Apostles Peter and Paul, all the Saints, and you, father, to pray for me to the Lord our God.",
        ans_10: "Amen",
        ans_11: "Amen",
        ans_12: "And your people shall rejoice in you.",
        ans_13: "And grant us your salvation.",
        ans_14: "And let my cry come unto you.",
        ans_15: "And with your spirit.",
        overallAccuracy: "Overall Accuracy" ,
        "In": "In",
        "nōmine": "name",
        "Patris": "Father",
        "et": "and",
        "Fīlii": "Son",
        "Spīritūs": "Spirit",
        "Sāncti": "Holy",
        "Amen": "Amen",
        "Introībo": "I will go",
        "ad": "to",
        "altāre": "altar",
        "Dei": "God",
        "Jūdica": "Judge",
        "me": "me",
        "Deus": "God",
        "discerne": "distinguish",
        "causam": "cause",
        "meam": "my",
        "de": "from",
        "gente": "nation",
        "nōn": "not",
        "sāncta": "holy",
        "ab": "from",
        "hōmine": "man",
        "inīquō": "unjust",
        "dolōso": "deceitful",
        "ērue": "deliver",
        "Quia": "Because",
        "tū": "you",
        "es": "are",
        "fortitūdo": "strength",
        "mea": "my",
        "Quāre": "Why",
        "repulistī": "have rejected",
        "tristis": "sad",
        "incedō": "I walk",
        "dum": "while",
        "affligit": "afflicts",
        "inimīcus": "enemy",
        "Ēmitte": "Send forth",
        "lūcem": "light",
        "tuam": "your",
        "veritātem": "truth",
        "ipsa": "they",
        "dēdūxērunt": "have led",
        "addūxērunt": "brought",
        "in": "into",
        "montem": "mountain",
        "sānctum": "holy",
        "tuum": "your",
        "tabernācula": "tabernacles",
        "Confitébor": "I will praise",
        "tibi": "to you",
        "cithāra": "harp",
        "ānima": "soul",
        "conturbāris": "are you troubled",
        "Spērā": "Hope",
        "quoniam": "because",
        "adhūc": "still",
        "confitébor": "I will praise",
        "illī": "to him",
        "salūtāre": "salvation",
        "vultus": "face",
        "Glōria": "Glory",
        "Fīliō": "Son",
        "Spīritūi": "Spirit",
        "Sānctō": "Holy",
        "Sīcut": "As",
        "erat": "was",
        "prīncipiō": "beginning",
        "nunc": "now",
        "semper": "always",
        "saecula": "ages",
        "saeculōrum": "of ages",
        "Adjutōrium": "Help",
        "nostrum": "our",
        "Dominī": "Lord",
        "Qui": "Who",
        "fēcit": "made",
        "caelum": "heaven",
        "terram": "earth",
        "laetificat": "gladdens",
        "juventūtem": "youth",
        "quare": "why",
        "quāre": "why",
        "conturbāris": "are you troubled",
        "Confiteor": "I confess",
        "omnipotenti": "almighty",
        "beātae": "blessed",
        "Marīae": "Mary",
        "semper": "always",
        "Virgīnī": "Virgin",
        "beātō": "blessed",
        "Michaēlī": "Michael",
        "Archangelō": "Archangel",
        "Joannī": "John",
        "Baptistae": "Baptist",
        "sānctīs": "holy",
        "Apostolīs": "Apostles",
        "Petrō": "Peter",
        "Paulō": "Paul",
        "omnibus": "all",
        "Sānctīs": "Saints",
        "vobis": "you (plural)",
        "frātrēs": "brethren",
        "peccāvī": "I have sinned",
        "nimis": "exceedingly",
        "cogitātiōne": "thought",
        "verbō": "word",
        "opere": "deed",
        "mea": "my",
        "culpa": "fault",
        "maxima": "most grievous",
        "Ideō": "therefore",
        "precor": "I beseech",
        "orāre": "to pray",
        "prō": "for",
        "mē": "me",
        "Miserēatur": "May have mercy",
        "tuī": "on you (singular)",
        "dimissīs": "having forgiven",
        "peccātīs": "sins",
        "perdūcat": "bring",
        "aeternam": "everlasting",
        "vestrī": "on you (plural)",
        "Indulgentiam": "pardon",
        "absolūtiōnem": "absolution",
        "remissiōnem": "remission",
        "tribuat": "grant",
        "nōbīs": "us",
        "misericors": "merciful",
        "conversus": "turned",
        "vivificābīs": "bring to life",
        "plēbs": "people",
        "laetābitur": "will rejoice",
        "Ostende": "Show",
        "misericordiam": "mercy",
        "salūtāre": "salvation",
        "exaudī": "hear",
        "ōrātiōnem": "prayer",
        "clāmor": "cry",
        "veniat": "come",
        "Dominus": "Lord",
        "vōbīscum": "with you",
        "spīritū": "spirit"
      },
      es: {
        previous: "Anterior",
        next: "Siguiente",
        hideanswer: "Ocultar Respuesta",
        showanswer: "Mostrar Respuesta",
        youranswer: "Tu Respuesta",
        correctanswer: "Respuesta Correcta", 
        translation: "Traducción",
        prompt: "Indicación",
        title_1: "Memorización de Frases Latinas",
        prompt_1: "En el nombre del Padre, y del Hijo, y del Espíritu Santo. Amén. Me acercaré al altar de Dios.",
        prompt_2: "Júzgame, oh Dios, y defiende mi causa contra gente no santa: líbrame del hombre inicuo y engañoso.",
        prompt_3: "Envía tu luz y tu verdad: ellas me guiarán y me llevarán a tu santo monte, y a tus tabernáculos.",
        prompt_4: "Te alabaré con el arpa, oh Dios, Dios mío: ¿por qué estás triste, alma mía, y por qué te turbas?",
        prompt_5: "Gloria al Padre, y al Hijo, y al Espíritu Santo.",
        prompt_6: "Me acercaré al altar de Dios.",
        prompt_7: "Nuestra ayuda está en el nombre del Señor",
        prompt_8: "Confieso ante Dios todopoderoso, ante la bienaventurada siempre Virgen María, ante el bienaventurado arcángel Miguel, ante el bienaventurado Juan Bautista, ante los santos apóstoles Pedro y Pablo, ante todos los santos y ante vosotros, hermanos, que he pecado mucho de pensamiento, palabra y obra: por mi culpa, por mi culpa, por mi grandísima culpa. Por eso ruego a la bienaventurada siempre Virgen María, al bienaventurado arcángel Miguel, al bienaventurado Juan Bautista, a los santos apóstoles Pedro y Pablo, a todos los santos y a vosotros, hermanos, que intercedáis por mí ante Dios nuestro Señor.",
        prompt_9: "Amén",
        prompt_10: "Tenga el Dios todopoderoso misericordia de vosotros, y perdonados vuestros pecados, os lleve a la vida eterna.",
        prompt_11: "El Señor todopoderoso y misericordioso nos conceda el perdón, la absolución y la remisión de nuestros pecados.",
        prompt_12: "Oh Dios, al volverte nos darás la vida.",
        prompt_13: "Muéstranos, Señor, tu misericordia.",
        prompt_14: "Señor, escucha mi oración.",
        prompt_15: "El Señor esté con vosotros.",
        ans_1: "A Dios que alegra mi juventud",
        ans_2: "Porque tú eres, Dios, mi fortaleza: ¿Por qué me has rechazado? ¿Y por qué voy triste mientras el enemigo me oprime?",
        ans_3: "Y me acercaré al altar de Dios: al Dios que alegra mi juventud.",
        ans_4: "Espera en Dios, porque aún he de alabarle: es mi salvación y mi Dios.",
        ans_5: "Como era en el principio, ahora y siempre, por los siglos de los siglos. Amén.",
        ans_6: "A Dios, que alegra mi juventud.",
        ans_7: "Que hizo el cielo y la tierra.",
        ans_8: "Tenga el Dios todopoderoso misericordia de ti, y perdonados tus pecados, te lleve a la vida eterna.",
        ans_9: "Yo confieso ante Dios todopoderoso, ante la bienaventurada siempre Virgen María, ante el bienaventurado arcángel Miguel, ante el bienaventurado Juan Bautista, ante los santos apóstoles Pedro y Pablo, ante todos los santos y ante ti, padre, que he pecado mucho de pensamiento, palabra y obra: por mi culpa, por mi culpa, por mi grandísima culpa. Por eso ruego a la bienaventurada siempre Virgen María, al bienaventurado arcángel Miguel, al bienaventurado Juan Bautista, a los santos apóstoles Pedro y Pablo, a todos los santos y a ti, padre, que intercedáis por mí ante Dios nuestro Señor.",
        ans_10: "Amén",
        ans_11: "Amén",
        ans_12: "Y tu pueblo se alegrará en ti.",
        ans_13: "Y danos tu salvación.",
        ans_14: "Y llegue hasta ti mi clamor.",
        ans_15: "Y con tu espíritu.",
        overallAccuracy: "Precisión General",
        "In": "En",
        "nōmine": "nombre",
        "Patris": "Padre",
        "et": "y",
        "Fīlii": "Hijo",
        "Spīritūs": "Espíritu",
        "Sāncti": "Santo",
        "Amen": "Amén",
        "Introībo": "Me acercaré",
        "ad": "a",
        "altāre": "altar",
        "Dei": "Dios",
        "Jūdica": "Juzga",
        "me": "me",
        "Deus": "Dios",
        "discerne": "distingue",
        "causam": "causa",
        "meam": "mi",
        "de": "de",
        "gente": "nación",
        "nōn": "no",
        "sāncta": "santa",
        "ab": "de",
        "hōmine": "hombre",
        "inīquō": "injusto",
        "dolōso": "engañoso",
        "ērue": "líbrame",
        "Quia": "Porque",
        "tū": "tú",
        "es": "eres",
        "fortitūdo": "fortaleza",
        "mea": "mi",
        "Quāre": "Por qué",
        "repulistī": "has rechazado",
        "tristis": "triste",
        "incedō": "camino",
        "dum": "mientras",
        "affligit": "aflige",
        "inimīcus": "enemigo",
        "Ēmitte": "Envía",
        "lūcem": "luz",
        "tuam": "tu",
        "veritātem": "verdad",
        "ipsa": "ellas",
        "dēdūxērunt": "han guiado",
        "addūxērunt": "han llevado",
        "in": "a",
        "montem": "monte",
        "sānctum": "santo",
        "tuum": "tu",
        "tabernācula": "tabernáculos",
        "Confitébor": "Alabaré",
        "tibi": "a ti",
        "cithāra": "arpa",
        "ānima": "alma",
        "conturbāris": "te turbas",
        "Spērā": "Espera",
        "quoniam": "porque",
        "adhūc": "aún",
        "confitébor": "alabaré",
        "illī": "a él",
        "salūtāre": "salvación",
        "vultus": "rostro",
        "Glōria": "Gloria",
        "Fīliō": "Hijo",
        "Spīritūi": "Espíritu",
        "Sānctō": "Santo",
        "Sīcut": "Como",
        "erat": "era",
        "prīncipiō": "principio",
        "nunc": "ahora",
        "semper": "siempre",
        "saecula": "siglos",
        "saeculōrum": "de los siglos",
        "Adjutōrium": "Auxilio",
        "nostrum": "nuestro",
        "Dominī": "Señor",
        "Qui": "Que",
        "fēcit": "hizo",
        "caelum": "cielo",
        "terram": "tierra",
        "laetificat": "alegra",
        "juventūtem": "juventud",
        "quare": "por qué",
        "quāre": "por qué",
        "conturbāris": "te turbas",
        "Confiteor": "Confieso",
        "omnipotenti": "todopoderoso",
        "beātae": "bienaventurada",
        "Marīae": "María",
        "semper": "siempre",
        "Virgīnī": "Virgen",
        "beātō": "bienaventurado",
        "Michaēlī": "Miguel",
        "Archangelō": "Arcángel",
        "Joannī": "Juan",
        "Baptistae": "Bautista",
        "sānctīs": "santos",
        "Apostolīs": "Apóstoles",
        "Petrō": "Pedro",
        "Paulō": "Pablo",
        "omnibus": "todos",
        "Sānctīs": "Santos",
        "vobis": "vosotros",
        "frātrēs": "hermanos",
        "peccāvī": "he pecado",
        "nimis": "mucho",
        "cogitātiōne": "pensamiento",
        "verbō": "palabra",
        "opere": "obra",
        "mea": "mi",
        "culpa": "culpa",
        "maxima": "muy grande",
        "Ideō": "Por eso",
        "precor": "suplico",
        "orāre": "orar",
        "prō": "por",
        "mē": "mí",
        "Miserēatur": "Tenga misericordia",
        "tuī": "de ti",
        "dimissīs": "perdonados",
        "peccātīs": "pecados",
        "perdūcat": "lleve",
        "aeternam": "eterna",
        "vestrī": "de vosotros",
        "Indulgentiam": "Indulgencia",
        "absolūtiōnem": "absolución",
        "remissiōnem": "remisión",
        "tribuat": "conceda",
        "nōbīs": "nosotros",
        "misericors": "misericordioso",
        "conversus": "convertido",
        "vivificābīs": "vivificarás",
        "plēbs": "pueblo",
        "laetābitur": "se alegrará",
        "Ostende": "Muestra",
        "misericordiam": "misericordia",
        "salūtāre": "salvación",
        "exaudī": "escucha",
        "ōrātiōnem": "oración",
        "clāmor": "clamor",
        "veniat": "venga",
        "Dominus": "Señor",
        "vōbīscum": "con vosotros",
        "spīritū": "espíritu"
      },
      zh: {
        previous: "上一页",
        next: "下一页",
        hideanswer: "隐藏答案",
        showanswer: "显示答案",
        youranswer: "你的答案",
        translation: "翻译",
        prompt: "提示",
        correctanswer: "正确答案",
        title_1: "拉丁短语记忆",
        prompt_1: "因父、及子、及圣神之名。阿们。我要走向天主的祭坛。",
        prompt_2: "天主，求你为我伸冤，驳斥不虔敬的民族，救我脱离诡诈邪恶的人。",
        prompt_3: "求你发出光明和真道，引导我，带我到你的圣山和居所。",
        prompt_4: "天主，我的天主，我要弹琴赞美你，我的灵魂，你为何悲伤，为何忧苦？",
        prompt_5: "愿光荣归于父、及子、及圣神。",
        prompt_6: "我要走向天主的祭坛。",
        prompt_7: "我们的救助是仰赖上主之名",
        prompt_8: "我向全能的天主，和你们各位弟兄，承认我在思、言、行为上的过失。我罪、我罪、我的重罪。为此，恳请终身童贞圣母玛利亚、天使长圣弥额尔、洗者圣若翰、圣伯多禄和圣保禄、诸位圣徒、以及你们各位弟兄，为我祈求上主、我们的天主。",
        prompt_9: "阿们",
        prompt_10: "愿全能的天主垂怜你们，赦免你们的罪，使你们得到永生。",
        prompt_11: "愿全能慈悲的主，赐给你们宽恕、赦免和罪过的赦免。",
        prompt_12: "天主，你一回转，必使我们复生。",
        prompt_13: "上主，求你向我们显示你的慈颜。",
        prompt_14: "上主，求你俯听我的祈祷。",
        prompt_15: "愿主与你们同在。",
        ans_1: "到使我青春欢乐的天主台前",
        ans_2: "天主，你是我的力量，为何抛弃我？为何让我在仇人压迫下徘徊忧伤？",
        ans_3: "我要走向天主的祭台，到使我青春欢乐的天主台前",
        ans_4: "该仰望天主，我还要颂扬祂，我面前的救主，我的天主",
        ans_5: "起初如何，今日亦然，直到永远。阿们",
        ans_6: "到使我青春欢乐的天主台前",
        ans_7: "祂创造了天地万物",
        ans_8: "愿全能的天主垂怜你，赦免你的罪过，使你获得永生",
        ans_9: "我向全能的天主和各位弟兄承认，我在思、言、行为上的过失。我罪、我罪、我的重罪。为此，恳请终身童贞圣母玛利亚、天使长圣弥额尔、洗者圣若翰、圣伯多禄和圣保禄、诸位圣徒，以及你——神父，为我祈求上主我们的天主",
        ans_10: "阿们",
        ans_11: "阿们",
        ans_12: "你的子民必因你而欢欣",
        ans_13: "将你的救恩赐给我们",
        ans_14: "愿我的祈祷上达于你",
        ans_15: "也与你的心灵同在",
        overallAccuracy: "总体准确率" ,
        "In": "因",
        "nōmine": "名",
        "Patris": "父",
        "et": "及",
        "Fīlii": "子",
        "Spīritūs": "圣神",
        "Sāncti": "圣",
        "Amen": "阿们",
        "Introībo": "我要走向",
        "ad": "到",
        "altāre": "祭台",
        "Dei": "天主",
        "Jūdica": "审判",
        "me": "我",
        "Deus": "天主",
        "discerne": "辨别",
        "causam": "案件",
        "meam": "我的",
        "de": "从",
        "gente": "民族",
        "nōn": "不",
        "sāncta": "圣洁",
        "ab": "从",
        "hōmine": "人",
        "inīquō": "不义",
        "dolōso": "欺诈",
        "ērue": "拯救",
        "Quia": "因为",
        "tū": "你",
        "es": "是",
        "fortitūdo": "力量",
        "mea": "我的",
        "Quāre": "为何",
        "repulistī": "拒绝",
        "tristis": "忧闷",
        "incedō": "行走",
        "dum": "当",
        "affligit": "压迫",
        "inimīcus": "仇敌",
        "Ēmitte": "发出",
        "lūcem": "光明",
        "tuam": "你的",
        "veritātem": "真理",
        "ipsa": "它们",
        "dēdūxērunt": "引导",
        "addūxērunt": "带领",
        "in": "进入",
        "montem": "山",
        "sānctum": "圣",
        "tuum": "你的",
        "tabernācula": "帐幕",
        "Confitébor": "我要赞美",
        "tibi": "向你",
        "cithāra": "琴",
        "ānima": "灵魂",
        "conturbāris": "烦扰",
        "Spērā": "盼望",
        "quoniam": "因为",
        "adhūc": "仍要",
        "confitébor": "赞美",
        "illī": "向他",
        "salūtāre": "救恩",
        "vultus": "面容",
        "Glōria": "光荣",
        "Fīliō": "子",
        "Spīritūi": "圣神",
        "Sānctō": "圣",
        "Sīcut": "如同",
        "erat": "起初",
        "prīncipiō": "原始",
        "nunc": "现在",
        "semper": "永远",
        "saecula": "世代",
        "saeculōrum": "万世",
        "Adjutōrium": "助佑",
        "nostrum": "我们的",
        "Dominī": "上主",
        "Qui": "祂",
        "fēcit": "创造",
        "caelum": "天",
        "terram": "地",
        "laetificat": "使欢欣",
        "juventūtem": "青春",
        "quare": "为何",
        "quāre": "为何",
        "conturbāris": "不安",
        "Confiteor": "我认罪",
        "omnipotenti": "全能",
        "beātae": "真福",
        "Marīae": "玛利亚",
        "semper": "永远",
        "Virgīnī": "童贞",
        "beātō": "真福",
        "Michaēlī": "弥额尔",
        "Archangelō": "总领天使",
        "Joannī": "若翰",
        "Baptistae": "洗者",
        "sānctīs": "诸位圣人",
        "Apostolīs": "宗徒",
        "Petrō": "伯多禄",
        "Paulō": "保禄",
        "omnibus": "所有",
        "Sānctīs": "圣人",
        "vobis": "你们",
        "frātrēs": "弟兄",
        "peccāvī": "我犯罪",
        "nimis": "极其",
        "cogitātiōne": "思念",
        "verbō": "言语",
        "opere": "行为",
        "mea": "我的",
        "culpa": "过失",
        "maxima": "重大",
        "Ideō": "为此",
        "precor": "恳求",
        "orāre": "祈祷",
        "prō": "为",
        "mē": "我",
        "Miserēatur": "垂怜",
        "tuī": "你",
        "dimissīs": "赦免",
        "peccātīs": "罪过",
        "perdūcat": "带领",
        "aeternam": "永生",
        "vestrī": "你们",
        "Indulgentiam": "宽恕",
        "absolūtiōnem": "赦免",
        "remissiōnem": "免除",
        "tribuat": "赐予",
        "nōbīs": "我们",
        "misericors": "仁慈",
        "conversus": "回转",
        "vivificābīs": "复苏",
        "plēbs": "子民",
        "laetābitur": "欢欣",
        "Ostende": "显示",
        "misericordiam": "仁慈",
        "salūtāre": "救恩",
        "exaudī": "俯听",
        "ōrātiōnem": "祈祷",
        "clāmor": "哀号",
        "veniat": "来到",
        "Dominus": "上主",
        "vōbīscum": "与你们同在",
        "spīritū": "心灵"
      }
};

export const TextProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const changeLanguage = (lang) => {
    setLanguage(lang);
  };

  const text = translations[language];

  return (
    <TextContext.Provider value={{ text, changeLanguage, currentLanguage: language }}>
      {children}
    </TextContext.Provider>
  );
};